# Generated by Django 3.1.5 on 2021-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20210217_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
