# Generated by Django 3.1.5 on 2021-02-17 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_auto_20210217_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='uModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskapp.taskmodel')),
            ],
        ),
    ]
