# Generated by Django 3.1.5 on 2021-02-18 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_auto_20210218_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='en_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(max_length=300),
        ),
    ]
