# Generated by Django 3.1.5 on 2021-02-18 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_auto_20210218_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='en_dt',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='ta_d',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='ta_t',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
