# Generated by Django 3.1.5 on 2021-02-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_auto_20210218_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='ta_t',
        ),
    ]
