# Generated by Django 3.1.5 on 2021-02-18 08:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_remove_taskmodel_ta_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='ta_d',
            field=models.DateField(auto_now_add=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
