# Generated by Django 3.1.5 on 2021-02-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0016_auto_20210218_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='ta_d',
            new_name='timestamp',
        ),
    ]
