# Generated by Django 3.1.5 on 2021-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_auto_20210218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
