# Generated by Django 3.1.5 on 2021-02-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_auto_20210218_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='timestamp',
        ),
    ]
