# Generated by Django 3.1.5 on 2021-02-18 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_remove_taskmodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
