# Generated by Django 3.1.5 on 2021-02-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0020_taskmodel_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskmodel',
            table='tasks',
        ),
    ]
