# Generated by Django 3.1.5 on 2021-02-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0021_auto_20210223_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelTable(
            name='taskmodel',
            table=None,
        ),
    ]
